#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
 	echo "Starting network..."
	/sbin/ifup -a
	/bin/echo -e "w 0x7200 0x1f0000\nw 0x7206 0x0140\nq\n" | /usr/sbin/regs_bin //sys/bus/spi/devices/spi1.0	
	;;
  stop)
	printf "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

