#!/bin/sh
#
# Start the network....
#

# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
 	echo "Starting network..."
	/sbin/ifup -a
	/bin/echo -e "ww 1f8001 0019\nww 1f0004 1a0\nww 1f0000 1340\nq\n" | /usr/sbin/regs_bin //sys/bus/spi/devices/spi1.0	
	;;
  stop)
	printf "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

